insert into lang (iso, lang) values
    ('ab', 'Abkhazian'),
    ('aa', 'Afar'),
    ('af', 'Afrikaans'),
    ('ak', 'Akan'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('an', 'Aragonese'),
    ('hy', 'Armenian'),
    ('as', 'Assamese'),
    ('av', 'Avaric'),
    ('ae', 'Avestan'),
    ('ay', 'Aymara'),
    ('az', 'Azerbaijani'),
    ('bm', 'Bambara'),
    ('ba', 'Bashkir'),
    ('eu', 'Basque'),
    ('be', 'Belarusian'),
    ('bn', 'Bengali'),
    ('bh', 'Bihari'),
    ('bi', 'Bislama'),
    ('bs', 'Bosnian'),
    ('br', 'Breton'),
    ('bg', 'Bulgarian'),
    ('my', 'Burmese'),
    ('ca', 'Catalan'),
    ('ch', 'Chamorro'),
    ('ce', 'Chechen'),
    ('ny', 'Chichewa'),
    ('zh', 'Chinese'),
    ('zh-Hans', 'Chinese (Simplified)'),
    ('zh-Hant', 'Chinese (Traditional)'),
    ('cv', 'Chuvash'),
    ('kw', 'Cornish'),
    ('co', 'Corsican'),
    ('cr', 'Cree'),
    ('hr', 'Croatian'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('dv', 'Divehi'),
    ('nl', 'Dutch'),
    ('dz', 'Dzongkha'),
    ('en', 'English'),
    ('eo', 'Esperanto'),
    ('et', 'Estonian'),
    ('ee', 'Ewe'),
    ('fo', 'Faeroese'),
    ('fj', 'Fijian'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('ff', 'Fulah'),
    ('gl', 'Galician'),
    ('lg', 'Ganda'),
    ('ka', 'Georgian'),
    ('de', 'German'),
    ('el', 'Greek'),
    ('gn', 'Guarani'),
    ('gu', 'Gujarati'),
    ('ht', 'Haitian'),
    ('ha', 'Hausa'),
    ('he', 'Hebrew'),
    ('hz', 'Herero'),
    ('hi', 'Hindi'),
    ('ho', 'Hiri Motu'),
    ('hu', 'Hungarian'),
    ('is', 'Icelandic'),
    ('io', 'Ido'),
    ('ig', 'Igbo'),
    ('id', 'Indonesian'),
    ('ia', 'Interlingua'),
    ('ie', 'Interlingue'),
    ('iu', 'Inuktitut'),
    ('ik', 'Inupiaq'),
    ('ga', 'Irish'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('jv', 'Javanese'),
    ('kl', 'Kalaallisut'),
    ('kn', 'Kannada'),
    ('kr', 'Kanuri'),
    ('ks', 'Kashmiri'),
    ('kk', 'Kazakh'),
    ('km', 'Khmer'),
    ('ki', 'Kikuyu'),
    ('rw', 'Kinyarwanda'),
    ('ky', 'Kirghiz'),
    ('rn', 'Kirundi'),
    ('kv', 'Komi'),
    ('kg', 'Kongo'),
    ('ko', 'Korean'),
    ('ku', 'Kurdish'),
    ('kj', 'Kwanyama'),
    ('lo', 'Lao'),
    ('la', 'Latin'),
    ('lv', 'Latvian'),
    ('li', 'Limburgish'),
    ('ln', 'Lingala'),
    ('lt', 'Lithuanian'),
    ('lu', 'Luba-Katanga'),
    ('lb', 'Luxembourgish'),
    ('mk', 'Macedonian'),
    ('mg', 'Malagasy'),
    ('ms', 'Malay'),
    ('ml', 'Malayalam'),
    ('mt', 'Maltese'),
    ('gv', 'Manx'),
    ('mi', 'Maori'),
    ('mr', 'Marathi'),
    ('mh', 'Marshallese'),
    ('mo', 'Moldavian'),
    ('mn', 'Mongolian'),
    ('na', 'Nauru'),
    ('nv', 'Navajo'),
    ('ng', 'Ndonga'),
    ('ne', 'Nepali'),
    ('nd', 'North Ndebele'),
    ('se', 'Northern Sami'),
    ('no', 'Norwegian'),
    ('nb', 'Norwegian Bokmål'),
    ('nn', 'Norwegian Nynorsk'),
    ('oc', 'Occitan'),
    ('oj', 'Ojibwa'),
    ('cu', 'Old Church Slavonic'),
    ('or', 'Oriya'),
    ('om', 'Oromo'),
    ('os', 'Ossetian'),
    ('ps', 'Pashto'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('fa', 'Persian'),
    ('pi', 'Päli'),
    ('pa', 'Panjabi'),
    ('qu', 'Quechua'),
    ('rc', 'Reunionese'),
    ('rm', 'Romansh'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('sm', 'Samoan'),
    ('sg', 'Sango'),
    ('sa', 'Sanskrit'),
    ('sc', 'Sardinian'),
    ('gd', 'Scottish Gaelic'),
    ('sr', 'Serbian'),
    ('sh', 'Serbo-Croatian'),
    ('sn', 'Shona'),
    ('ii', 'Sichuan Yi'),
    ('sd', 'Sindhi'),
    ('si', 'Sinhalese'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('so', 'Somali'),
    ('st', 'Sotho'),
    ('nr', 'South Ndebele'),
    ('es', 'Spanish'),
    ('su', 'Sundanese'),
    ('sw', 'Swahili'),
    ('ss', 'Swati'),
    ('sv', 'Swedish'),
    ('tl', 'Tagalog'),
    ('ty', 'Tahitian'),
    ('tg', 'Tajik'),
    ('ta', 'Tamil'),
    ('tt', 'Tatar'),
    ('te', 'Telugu'),
    ('th', 'Thai'),
    ('bo', 'Tibetan'),
    ('ti', 'Tigrinya'),
    ('to', 'Tonga'),
    ('ts', 'Tsonga'),
    ('tn', 'Tswana'),
    ('tr', 'Turkish'),
    ('tk', 'Turkmen'),
    ('tw', 'Twi'),
    ('ug', 'Uighur'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('uz', 'Uzbek'),
    ('ve', 'Venda'),
    ('vi', 'Viêt Namese'),
    ('vo', 'Volapük'),
    ('wa', 'Walloon'),
    ('cy', 'Welsh'),
    ('fy', 'Western Frisian'),
    ('wo', 'Wolof'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('yo', 'Yoruba'),
    ('za', 'Zhuang'),
    ('zu', 'Zulu');

insert into country (country, iso, code) values
    ('Afghanistan', 'AF', 004),
    ('Åland Islands', 'AX', 248),
    ('Albania', 'AL', 008),
    ('Algeria', 'DZ', 012),
    ('American Samoa', 'AS', 016),
    ('Andorra', 'AD', 020),
    ('Angola', 'AO', 024),
    ('Anguilla', 'AI', 660),
    ('Antartica', 'AQ', 010),
    ('Antigua and Barbuda', 'AG', 028),
    ('Argentina', 'AR', 032),
    ('Armenia', 'AM', 051),
    ('Aruba', 'AW', 533),
    ('Australia', 'AU', 036),
    ('Austria', 'AT', 040),
    ('Azerbaijan', 'AZ', 031),
    ('Bahamas', 'BS', 044),
    ('Bahrain', 'BH', 048),
    ('Bangladesh', 'BD', 050),
    ('Barbados', 'BB', 052),
    ('Belarus', 'BY', 112),
    ('Belgium', 'BE', 056),
    ('Belize', 'BZ', 084),
    ('Benin', 'BJ', 204),
    ('Bermuda', 'BM', 060),
    ('Bhutan', 'BT', 064),
    ('Bolivia (Plurinational State of)', 'BO', 068),
    ('Bonaire, Sint Eustatius and Saba', 'BQ', 535),
    ('Bosnia and Herzegovina', 'BA', 070),
    ('Botswana', 'BW', 072),
    ('Bouvet Island', 'BV', 074),
    ('Brazil', 'BR', 076),
    ('British Indian Ocean Territory', 'IO', 086),
    ('Brunei Darussalam', 'BN', 096),
    ('Bulgaria', 'BG', 100),
    ('Burkina Faso', 'BF', 854),
    ('Burundi', 'BI', 108),
    ('Cabo Verde', 'CV', 132),
    ('Cambodia', 'KH', 116),
    ('Cameroon', 'CM', 120),
    ('Canada', 'CA', 124),
    ('Cayman Islands', 'KY', 136),
    ('Central African Republic', 'CF', 140),
    ('Chad', 'TD', 148),
    ('Chile', 'CL', 152),
    ('China', 'CN', 156),
    ('Christmas Island', 'CX', 162),
    ('Cocos (Keeling) Islands', 'CC', 166),
    ('Colombia', 'CO', 170),
    ('Comoros', 'KM', 174),
    ('Congo', 'CG', 178),
    ('Congo (Democratic Republic of the)', 'CD', 180),
    ('Cook Islands', 'CK', 184),
    ('Costa Rica', 'CR', 188),
    ('Côte d''Ivoire', 'CI', 384),
    ('Croatia', 'HR', 191),
    ('Cuba', 'CU', 192),
    ('Curaçao', 'CW', 531),
    ('Cyprus', 'CY', 196),
    ('Czechia', 'CZ', 203),
    ('Denmark', 'DK', 208),
    ('Djibouti', 'DJ', 262),
    ('Dominica', 'DM', 212),
    ('Dominica Republic', 'DO', 214),
    ('Ecuador', 'EC', 218),
    ('Egypt', 'EG', 818),
    ('El Salvador', 'SV', 222),
    ('Equatorial Guinea', 'GQ', 226),
    ('Eritrea', 'ER', 232),
    ('Estonia', 'EE', 233),
    ('Ethiopia', 'ET', 231),
    ('Falkland Islands (Malvinas)', 'FK', 238),
    ('Faroe Islands', 'FO', 234),
    ('Fiji', 'FJ', 242),
    ('Finland', 'FI', 246),
    ('France', 'FR', 250),
    ('French Guiana', 'GF', 254),
    ('French Polynesia', 'PF', 258),
    ('French Southern Territories', 'TF', 260),
    ('Gabon', 'GA', 266),
    ('Gambia', 'GM', 270),
    ('Georgia', 'GE', 268),
    ('Germany', 'DE', 276),
    ('Ghana', 'GH', 288),
    ('Gibraltar', 'GI', 292),
    ('Greece', 'GR', 300),
    ('Greenland', 'GL', 304),
    ('Grenada', 'GD', 308),
    ('Guadeloupe', 'GP', 312),
    ('Guam', 'GU', 316),
    ('Guatemala', 'GT', 320),
    ('Guernsey', 'GG', 831),
    ('Guinea', 'GN', 324),
    ('Guinea-Bissau', 'GW', 624),
    ('Guyana', 'GY', 328),
    ('Haiti', 'HT', 332),
    ('Heard Island and McDonald Islands', 'HM', 334),
    ('Holy See', 'VA', 336),
    ('Honduras', 'HN', 340),
    ('Hong Kong', 'HK', 344),
    ('Hungary', 'HU', 348),
    ('Iceland', 'IS', 352),
    ('India', 'IN', 356),
    ('Indonesia', 'ID', 360),
    ('Iran (Islamic Republic of)', 'IR', 364),
    ('Iraq', 'IQ', 368),
    ('Ireland', 'IE', 372),
    ('Isle of Man', 'IM', 833),
    ('Israel', 'IL', 376),
    ('Italy', 'IT', 380),
    ('Jamaica', 'JM', 388),
    ('Japan', 'JP', 392),
    ('Jersey', 'JE', 832),
    ('Jordan', 'JO', 400),
    ('Kazakhstan', 'KZ', 398),
    ('Kenya', 'KE', 404),
    ('Kiribati', 'KI', 296),
    ('Korea (Democratic People''s Republic of)', 'KP', 408),
    ('Korea (Republic of)', 'KR', 410),
    ('Kuwait', 'KW', 414),
    ('Kyrgyzstan', 'KG', 417),
    ('Lao People'' Democratic Republic', 'LA', 418),
    ('Latvia', 'LV', 428),
    ('Lebanon', 'LB', 422),
    ('Lesotho', 'LS', 426),
    ('Liberia', 'LR', 430),
    ('Libya', 'LY', 434),
    ('Liechtenstein', 'LI', 438),
    ('Lithuania', 'LT', 440),
    ('Luxembourg', 'LU', 442),
    ('Macao', 'MO', 446),
    ('Macedonia (the former Yugoslav Republic of)', 'MK', 807),
    ('Madagascar', 'MG', 450),
    ('Malawi', 'MW', 454),
    ('Malaysia', 'MY', 458),
    ('Maldives', 'MV', 462),
    ('Mali', 'ML', 466),
    ('Malta', 'MT', 470),
    ('Marshal Islands', 'MH', 584),
    ('Martinique', 'MQ', 474),
    ('Mauritania', 'MR', 478),
    ('Mauritius', 'MU', 480),
    ('Mayotte', 'YT', 175),
    ('Mexico', 'MX', 484),
    ('Micronesia (Federated States of)', 'FM', 583),
    ('Moldova (Republic of)', 'MD', 498),
    ('Monaco', 'MC', 492),
    ('Mongolia', 'MN', 496),
    ('Montenegro', 'ME', 499),
    ('Montserrat', 'MS', 500),
    ('Morocco', 'MA', 504),
    ('Mozambique', 'MZ', 508),
    ('Myanmar', 'MM', 104),
    ('Namibia', 'NA', 516),
    ('Nauru', 'NR', 520),
    ('Nepal', 'NP', 524),
    ('Netherlands', 'NL', 528),
    ('New Caledonia', 'NC', 540),
    ('New Zealand', 'NZ', 554),
    ('Nicaragua', 'NI', 558),
    ('Niger', 'NE', 562),
    ('Nigeria', 'NG', 566),
    ('Niue', 'NU', 570),
    ('Norfolk Island', 'NF', 574),
    ('Northern Mariana Islands', 'MP', 580),
    ('Norway', 'NO', 578),
    ('Oman', 'OM', 512),
    ('Pakistan', 'PK', 586),
    ('Palau', 'PW', 585),
    ('Palestine, State of', 'PS', 275),
    ('Panama', 'PA', 591),
    ('Papua New Guina', 'PG', 598),
    ('Paraguay', 'PY', 600),
    ('Peru', 'PE', 604),
    ('Philippines', 'PH', 608),
    ('Pitcairn', 'PN', 612),
    ('Poland', 'PL', 616),
    ('Portugal', 'PT', 620),
    ('Puerto Rico', 'PR', 630),
    ('Qatar', 'QA', 634),
    ('Réunion', 'RE', 638),
    ('Romania', 'RO', 642),
    ('Russian Federation', 'RU', 643),
    ('Rwanda', 'RW', 646),
    ('Saint Barthélemy', 'BL', 652),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 654),
    ('Saint Kitts and Nevis', 'KN', 659),
    ('Saint Lucia', 'LC', 662),
    ('Saint Martin (French part)', 'MF', 663),
    ('Saint Pierre and Miquelon', 'PM', 666),
    ('Saint Vincent and the Grenadines', 'VC', 670),
    ('Samoa', 'WS', 882),
    ('San Marino', 'SM', 674),
    ('Sao Tome and Principe', 'ST', 678),
    ('Saudi Arabia', 'SA', 682),
    ('Senegal', 'SN', 686),
    ('Serbia', 'RS', 688),
    ('Seychelles', 'SC', 690),
    ('Sierra Leone', 'SL', 694),
    ('Singapore', 'SG', 702),
    ('Sint Maarten (Dutch part)', 'SX', 534),
    ('Slovakia', 'SK', 703),
    ('Slovenia', 'SI', 705),
    ('Solomon Islands', 'SB', 090),
    ('Somalia', 'SO', 706),
    ('South Africa', 'ZA', 710),
    ('South Georgia and the South Sandwich Islands', 'GS', 239),
    ('South Soudan', 'SS', 728),
    ('Spain', 'ES', 724),
    ('Sri Lanka', 'LK', 144),
    ('Sudan', 'SD', 729),
    ('Suriname', 'SR', 740),
    ('Svalbard and Jan Mayen', 'SJ', 744),
    ('Swaziland', 'SZ', 748),
    ('Sweden', 'SE', 752),
    ('Switzerland', 'CH', 756),
    ('Syrian Arab Republic', 'SY', 760),
    ('Taiwan, Province of China', 'TW', 158),
    ('Tajikistan', 'TJ', 762),
    ('Tanzania, United Republic of', 'TZ', 834),
    ('Thailand', 'TH', 764),
    ('Timor-Leste', 'TL', 626),
    ('Togo', 'TG', 768),
    ('Tokelau', 'TK', 772),
    ('Tonga', 'TO', 776),
    ('Trinidad and Tobago', 'TT', 780),
    ('Tunisia', 'TN', 788),
    ('Turkey', 'TR', 792),
    ('Turkmenistan', 'TM', 795),
    ('Turks and Caicos Islands', 'TC', 796),
    ('Tuvalu', 'TV', 798),
    ('Uganda', 'UG', 800),
    ('Ukraine', 'UA', 804),
    ('United Arab Emirates', 'AE', 784),
    ('United Kingdom of Great Britain and Northern Ireland', 'GB', 826),
    ('United States of America', 'US', 840),
    ('United States Minor Outlying Islands', 'UM', 581),
    ('Uruguay', 'UY', 858),
    ('Uzbekistan', 'UZ', 860),
    ('Vanuatu', 'VU', 548),
    ('Venezuela (Bolivarian Republic of)', 'VE', 862),
    ('Viet Nam', 'VN', 704),
    ('Virgin Islands (British)', 'VG', 092),
    ('Virgin Islands (US)', 'VI', 850),
    ('Wallis and Futuna', 'WF', 876),
    ('Western Sahara', 'EH', 732),
    ('Yemen', 'YE', 887),
    ('Zambia', 'ZM', 894),
    ('Zimbabwe', 'ZW', 714);

-- TODO: FIX
--
--insert into locale (lang_id, country_id, code)
--    select l.id as lang_id, c.id as country_id, lc.code as code
--    from lang l
--        join country c on true
--    where code = lc.code
--    union
--    SELECT * FROM (VALUES ('fr_FR'), ('en_GB'), ('it_IT')) as lc(code);

insert into user_role (title, description, is_radio, is_salon) values
    ('Owner', 'Creator & owner of an instance (Super User)', true, true),
    ('Admin', 'Administrator of an instance, user manager', true, true),
    ('Mixer', 'Moderator & dj', false, true),
    ('Moderator', 'Moderate salons', true, true),
    ('Subscriber', 'User that has unlimited access to a radio', true, false),
    ('Guest', 'User that has access to a radio', true, false),
    ('Viewer', 'User that is currently in the room', false, true);

insert into user_status (title, description, is_radio, is_salon) values
    ('Online', 'User currently here', true, true),
    ('Offline', 'User currently absent', true, true),
    ('Banned', 'Access forbidden for this user', true, false);

insert into abstract_user (id) values
    ('71b3c20c-a218-4b5e-b5c2-d3c5127c9257');

insert into metadata (id, creation_user_id) values
    ('59b5d139-8adc-4d6b-8253-bffd9ba5e848', '71b3c20c-a218-4b5e-b5c2-d3c5127c9257');

insert into user_login (metadata_id, user_id, login) values
    ('59b5d139-8adc-4d6b-8253-bffd9ba5e848', '71b3c20c-a218-4b5e-b5c2-d3c5127c9257', 'tatav');

insert into shadow_passwd (metadata_id, user_id, hash) values
    ('59b5d139-8adc-4d6b-8253-bffd9ba5e848', '71b3c20c-a218-4b5e-b5c2-d3c5127c9257', '');

insert into platform_user (metadata_id, abstract_id, firstname, lastname, email, birthday) values
    ('59b5d139-8adc-4d6b-8253-bffd9ba5e848', '71b3c20c-a218-4b5e-b5c2-d3c5127c9257', 'Maxime', 'Tavernier', 'maximetavernier92@email.com', '1991-10-21');

insert into preferences (metadata_id, user_id) values
    ('59b5d139-8adc-4d6b-8253-bffd9ba5e848', '71b3c20c-a218-4b5e-b5c2-d3c5127c9257');

